import { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { checkProof, INITIAL_GRID, prettyPrintArray, Footer } from './util'
import {Md5} from 'ts-md5/dist/md5';

const Verify: NextPage = () => {
  const initVal = prettyPrintArray(INITIAL_GRID)
  const [unsolvedGridText, setUnsolvedGridText] = useState(initVal);
  const [proofText, setProofText] = useState('');
  const [status, setStatus] = useState(false);
  const [hash, setHash] = useState('');

  function computePublicSignals(unsolvedGrid: number[][]) {
    var res = []
    for (var i = 0;i < unsolvedGrid.length;i++) {
      for (var j = 0;j < unsolvedGrid[i].length;j++) res.push(unsolvedGrid[i][j].toString());
    }
    return res;
  }

  async function computeAndCheckProof() {
    const unsolvedGrid = JSON.parse(unsolvedGridText);
    const proof = JSON.parse(proofText);
    const publicSignals = computePublicSignals(unsolvedGrid);
    setHash(Md5.hashStr(JSON.stringify(unsolvedGrid)).slice(0, 6));

    const res = await checkProof(proof, publicSignals);
    setStatus(res);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Snarky Sudoku</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Snarky Sudoku
        </h1>

        <p className={styles.description}>
          Check a proof for unsolved sudoku
          <code className={styles.code}>{hash}</code>
        </p>

        <div className={styles.grid}>
          <div>
            <p className={styles.description}>Unsolved grid</p>
            <textarea rows={10} className={styles.textarea} value={unsolvedGridText} onChange={event => setUnsolvedGridText(event.target.value)} />
          </div>
          <div>
          <p className={styles.description}>Proof</p>
          <textarea rows={10} className={styles.textarea} value={proofText} onChange={event => setProofText(event.target.value)} />
          </div>
        </div>

        <button onClick={computeAndCheckProof}>
          Check Proof
        </button>

        <p className={styles.description}>{status}</p>
        {status ? (
          <>
            <p className={styles.description}>✅ Correct proof</p>
            <p>This proof corresponds to a valid preimage for this unsolved grid.</p>
          </>
          ) : (
          <>
            <p className={styles.description}>❌ Invalid proof</p>
          </>
          )
        }


      </main>

      <Footer />
    </div>
  )
}

export default Verify